# Generated by Django 4.2.6 on 2023-10-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(default=0, upload_to='post'),
            preserve_default=False,
        ),
    ]
