# Generated by Django 4.2.6 on 2023-10-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auth',
            name='image',
            field=models.FileField(default=0, upload_to='pro_pic'),
            preserve_default=False,
        ),
    ]
